// apps/platform/src/routes/profile.page.tsx
import { Link } from "@tanstack/react-router";
import { getChallengeCollections, getRankProgress } from "@foruntendo/challenges";
import { useDatabaseSnapshot } from "../hooks/useDatabaseSnapshot.ts";
import { getMmrScore, getPassedChallengeIds } from "../lib/progress.ts";

function formatDate(value: string): string {
  return new Intl.DateTimeFormat("ru", {
    dateStyle: "medium",
    timeStyle: "short",
  }).format(new Date(value));
}

export function ProfilePage() {
  const { attempts } = useDatabaseSnapshot();

  const passed = attempts.filter((attempt) => attempt.status === "passed").length;
  const passedChallengeIds = getPassedChallengeIds(attempts);
  const rankScore = getMmrScore(attempts);
  const rankProgress = getRankProgress(rankScore);
  const collections = getChallengeCollections();

  return (
    <div className="container">
      <div className="page-header">
        <h1>Профиль</h1>
        <p className="page-subtitle">Все сохраненные попытки решения и результаты тестов.</p>
      </div>

      <section className="profile-rank-panel">
        <div className="profile-rank-main">
          <span className="profile-rank-kicker">Текущий уровень</span>
          <div className="profile-rank-value">{rankProgress.title}</div>
          <div className="profile-rank-title">{rankProgress.score} MMR</div>
          <Link to="/profile/rank" className="profile-rank-link">
            Подробнее
          </Link>
        </div>
        <div className="profile-rank-progress">
          <div className="profile-rank-score">
            <span>{rankProgress.score} MMR</span>
            <span>
              {rankProgress.nextTitle
                ? `до уровня ${rankProgress.nextTitle}: ${rankProgress.remainingScore} MMR`
                : "верхний уровень текущей шкалы"}
            </span>
          </div>
          <div className="skill-progress" aria-label={`${rankProgress.progressPercent}%`}>
            <span style={{ width: `${rankProgress.progressPercent}%` }} />
          </div>
          <p>
            MMR начисляется один раз за первую успешную сдачу задачи: F1 дает 2, F2 - 3, F3 - 8, F4
            - 21, F5 - 55, F6 - 149, F7 - 404, F8 - 1097.
          </p>
        </div>
      </section>

      <div className="profile-stats">
        <div>
          <span className="knowledge-stat-value">{attempts.length}</span>
          <span className="knowledge-stat-label">попыток</span>
        </div>
        <div>
          <span className="knowledge-stat-value">{passed}</span>
          <span className="knowledge-stat-label">успешных</span>
        </div>
        <div>
          <span className="knowledge-stat-value">
            {attempts.length === 0 ? 0 : Math.round((passed / attempts.length) * 100)}%
          </span>
          <span className="knowledge-stat-label">проходов</span>
        </div>
      </div>

      <section className="skill-section">
        <div className="section-heading">
          <h2>Навыки</h2>
          <p>Прогресс растет, когда задача из сборника успешно проходит все тесты.</p>
        </div>
        <div className="skill-list">
          {collections.map((collection) => {
            const completed = collection.challengeIds.filter((id) =>
              passedChallengeIds.has(id),
            ).length;
            const percent =
              collection.challengeCount === 0
                ? 0
                : Math.round((completed / collection.challengeCount) * 100);

            return (
              <article key={collection.id} className="skill-row">
                <div className="skill-row-header">
                  <div>
                    <div className="attempt-title">{collection.skillLabel}</div>
                    <div className="attempt-meta">{collection.tag}</div>
                  </div>
                  <span className="skill-score">
                    {completed}/{collection.challengeCount}
                  </span>
                </div>
                <div className="skill-progress" aria-label={`${percent}%`}>
                  <span style={{ width: `${percent}%` }} />
                </div>
              </article>
            );
          })}
        </div>
      </section>

      <div className="attempt-list">
        {attempts.map((attempt) => (
          <article key={attempt.id} className="attempt-row">
            <div>
              <div className="attempt-title">{attempt.challengeTitle}</div>
              <div className="attempt-meta">
                {formatDate(attempt.createdAt)} · {attempt.language}
              </div>
            </div>
            <div className="attempt-result">
              <span className={attempt.status === "passed" ? "test-passed" : "test-failed"}>
                {attempt.status === "passed" ? "пройдено" : "ошибка"}
              </span>
              <span>
                {attempt.passed}/{attempt.total || attempt.passed + attempt.failed} тестов
              </span>
            </div>
          </article>
        ))}
        {attempts.length === 0 && <p className="empty-state">Пока нет попыток.</p>}
      </div>
    </div>
  );
}

// apps/platform/src/routes/profile.page.svelte
<script lang="ts">
  import { getChallengeCollections, getRankProgress } from "@codenesis/challenges";
  import { attempts } from "../lib/database-store.ts";
  import { getMmrScore, getPassedChallengeIds } from "../lib/progress.ts";

  const collections = getChallengeCollections();
  const formatDate = (value: string) =>
    new Intl.DateTimeFormat("ru", { dateStyle: "medium", timeStyle: "short" }).format(
      new Date(value),
    );
  $: passed = $attempts.filter((attempt) => attempt.status === "passed").length;
  $: passedIds = getPassedChallengeIds($attempts);
  $: rank = getRankProgress(getMmrScore($attempts));
</script>

<div class="container">
  <div class="page-header"><h1>Профиль</h1><p class="page-subtitle">Все сохраненные попытки решения и результаты тестов.</p></div>
  <section class="profile-rank-panel"><div class="profile-rank-main"><span class="profile-rank-kicker">Текущий уровень</span><div class="profile-rank-value">{rank.title}</div><div class="profile-rank-title">{rank.score} MMR</div><a href="#/profile/rank" class="profile-rank-link">Подробнее</a></div><div class="profile-rank-progress"><div class="profile-rank-score"><span>{rank.score} MMR</span><span>{rank.nextTitle ? `до уровня ${rank.nextTitle}: ${rank.remainingScore} MMR` : "верхний уровень текущей шкалы"}</span></div><div class="skill-progress" aria-label={`${rank.progressPercent}%`}><span style={`width:${rank.progressPercent}%`}></span></div><p>MMR начисляется один раз за первую успешную сдачу задачи.</p></div></section>
  <div class="profile-stats"><div><span class="knowledge-stat-value">{$attempts.length}</span><span class="knowledge-stat-label">попыток</span></div><div><span class="knowledge-stat-value">{passed}</span><span class="knowledge-stat-label">успешных</span></div><div><span class="knowledge-stat-value">{$attempts.length ? Math.round((passed / $attempts.length) * 100) : 0}%</span><span class="knowledge-stat-label">проходов</span></div></div>
  <section class="skill-section"><div class="section-heading"><h2>Навыки</h2><p>Прогресс растет, когда задача успешно проходит все тесты.</p></div><div class="skill-list">{#each collections as collection}<article class="skill-row"><div class="skill-row-header"><div><div class="attempt-title">{collection.skillLabel}</div><div class="attempt-meta">{collection.tag}</div></div><span class="skill-score">{collection.challengeIds.filter((id) => passedIds.has(id)).length}/{collection.challengeCount}</span></div><div class="skill-progress"><span style={`width:${collection.challengeCount ? Math.round(collection.challengeIds.filter((id) => passedIds.has(id)).length / collection.challengeCount * 100) : 0}%`}></span></div></article>{/each}</div></section>
  <div class="attempt-list">{#each $attempts as attempt}<article class="attempt-row"><div><div class="attempt-title">{attempt.challengeTitle}</div><div class="attempt-meta">{formatDate(attempt.createdAt)} · {attempt.language}</div></div><div class="attempt-result"><span class:test-passed={attempt.status === "passed"} class:test-failed={attempt.status !== "passed"}>{attempt.status === "passed" ? "пройдено" : "ошибка"}</span><span>{attempt.passed}/{attempt.total || attempt.passed + attempt.failed} тестов</span></div></article>{:else}<p class="empty-state">Пока нет попыток.</p>{/each}</div>
</div>
