// apps/platform/src/components/catalog/ChallengeCard.tsx
import type { ChallengeMeta } from "@foruntendo/challenges";
import { getChallengeLevelLabel, getRankBand } from "@foruntendo/challenges";

interface ChallengeCardProps {
  challenge: ChallengeMeta;
  onClick: () => void;
}

export function ChallengeCard({ challenge, onClick }: ChallengeCardProps) {
  const rankBand = getRankBand(challenge.rank);

  return (
    <article
      className="challenge-card"
      onClick={onClick}
      role="button"
      tabIndex={0}
      onKeyDown={(e) => {
        if (e.key === "Enter") onClick();
      }}
    >
      <div className="card-header">
        <span className="badge badge-rank">{getChallengeLevelLabel(challenge.rank)}</span>
        <span className="card-category">{challenge.group}</span>
      </div>
      <h3 className="card-title">{challenge.title}</h3>
      <p className="card-desc">{challenge.description.split("\n")[0]}</p>
      <div className="card-footer">
        <span className="card-rep">{rankBand.label}</span>
        <span className="card-rep">+{challenge.reputation} MMR</span>
        <span className="card-languages">{challenge.languages.join(", ")}</span>
      </div>
    </article>
  );
}

// apps/platform/src/components/catalog/ChallengeCard.svelte
<script lang="ts">
  import type { ChallengeMeta } from "@codenesis/challenges";
  import { getChallengeLevelLabel } from "@codenesis/challenges";

  export let challenge: ChallengeMeta = null!;
  export let onClick: () => void = () => undefined;

  $: tags = [...new Set([challenge.category, challenge.group, ...challenge.tags])].slice(0, 8);
</script>

<button class="challenge-card" type="button" on:click={onClick}>
  <div class="card-header">
    <span class="badge badge-rank">{getChallengeLevelLabel(challenge.rank)}</span>
  </div>
  <h3 class="card-title">{challenge.title}</h3>
  <div class="challenge-tags" aria-label="Теги задачи">
    {#each tags as tag (tag)}
      <span class="challenge-tag">{tag}</span>
    {/each}
  </div>
</button>
