// apps/platform/src/components/editor/EditorPanel.tsx
import Editor, { type OnMount } from "@monaco-editor/react";
import type { ChallengeFile } from "@foruntendo/challenges";
import { useCallback, useEffect, useMemo, useRef, useState } from "react";

interface EditorPanelProps {
  files: ChallengeFile[];
  fullTestFiles?: ChallengeFile[];
  onFileChange: (path: string, content: string) => void;
  onRunTests: () => void;
  onSave: (files: Record<string, string>) => Promise<void> | void;
  view: "code" | "tests" | "full-tests";
  theme: string;
  fontSize: number;
}

declare global {
  interface Window {
    __foruntendoSetEditorValue?: (value: string) => void;
  }
}

function languageFromPath(path: string): string {
  if (path.endsWith(".tsx")) return "typescriptreact";
  if (path.endsWith(".ts")) return "typescript";
  if (path.endsWith(".jsx")) return "javascriptreact";
  if (path.endsWith(".js")) return "javascript";
  if (path.endsWith(".css")) return "css";
  if (path.endsWith(".html")) return "html";
  if (path.endsWith(".json")) return "json";
  if (path.endsWith(".svelte")) return "html";
  if (path.endsWith(".vue")) return "html";
  return "plaintext";
}

export function EditorPanel({
  files,
  fullTestFiles = [],
  onFileChange,
  onRunTests,
  onSave,
  view,
  theme,
  fontSize,
}: EditorPanelProps) {
  const allPanelFiles = useMemo(() => {
    const publicPaths = new Set(files.map((file) => file.path));
    return [...files, ...fullTestFiles.filter((file) => !publicPaths.has(file.path))];
  }, [files, fullTestFiles]);
  const editableFiles = useMemo(
    () => files.filter((file) => !file.path.includes(".test.") && file.path !== "package.json"),
    [files],
  );
  const testFiles = useMemo(() => files.filter((file) => file.path.includes(".test.")), [files]);
  const visibleFiles =
    view === "full-tests" ? fullTestFiles : view === "tests" ? testFiles : editableFiles;
  const isReadOnly = view === "tests" || view === "full-tests";
  const editorRef = useRef<Parameters<OnMount>[0] | null>(null);
  const runTestsRef = useRef(onRunTests);
  const saveTimerRef = useRef<number | null>(null);
  const fileContentsRef = useRef<Record<string, string>>({});
  const dirtyRef = useRef(false);
  const saveCurrentStateRef = useRef<() => Promise<void>>(async () => {});

  const [activeFile, setActiveFile] = useState(visibleFiles[0]?.path ?? "");
  const [fileContents, setFileContents] = useState<Record<string, string>>(() =>
    Object.fromEntries(allPanelFiles.map((f) => [f.path, f.content])),
  );

  useEffect(() => {
    runTestsRef.current = onRunTests;
  }, [onRunTests]);

  useEffect(() => {
    const nextContents = Object.fromEntries(allPanelFiles.map((f) => [f.path, f.content]));
    setFileContents(nextContents);
    fileContentsRef.current = nextContents;
    dirtyRef.current = false;
  }, [allPanelFiles]);

  useEffect(() => {
    if (visibleFiles.length === 0) {
      if (activeFile !== "") setActiveFile("");
      return;
    }

    if (!visibleFiles.some((file) => file.path === activeFile)) {
      setActiveFile(visibleFiles[0]?.path ?? "");
    }
  }, [activeFile, visibleFiles]);

  const saveCurrentState = useCallback(async () => {
    if (editorRef.current && activeFile && !isReadOnly) {
      await editorRef.current.getAction("editor.action.formatDocument")?.run();
      const raw = editorRef.current.getValue();
      const collapsed = raw.replace(/\n{3,}/g, "\n\n").replace(/^\n+/, "").replace(/\n+$/, "\n");
      if (collapsed !== raw) editorRef.current.setValue(collapsed);
      const formatted = editorRef.current.getValue();
      fileContentsRef.current = { ...fileContentsRef.current, [activeFile]: formatted };
      setFileContents(fileContentsRef.current);
      onFileChange(activeFile, formatted);
    }

    dirtyRef.current = false;
    await onSave(fileContentsRef.current);
  }, [activeFile, isReadOnly, onFileChange, onSave]);

  useEffect(() => {
    saveCurrentStateRef.current = saveCurrentState;
  }, [saveCurrentState]);

  const handleChange = useCallback(
    (value: string | undefined) => {
      if (value === undefined || isReadOnly || !activeFile) return;
      const nextContents = { ...fileContentsRef.current, [activeFile]: value };
      fileContentsRef.current = nextContents;
      dirtyRef.current = true;
      setFileContents(nextContents);
      onFileChange(activeFile, value);

      if (saveTimerRef.current) {
        window.clearTimeout(saveTimerRef.current);
      }
      saveTimerRef.current = window.setTimeout(() => {
        void onSave(fileContentsRef.current);
        dirtyRef.current = false;
      }, 5000);
    },
    [activeFile, isReadOnly, onFileChange, onSave],
  );

  useEffect(() => {
    const handleKeyDown = (event: KeyboardEvent) => {
      const isSaveKey =
        event.code === "KeyS" || event.key === "s" || event.key === "S" || event.key === "ы" || event.key === "Ы";
      if ((event.ctrlKey || event.metaKey) && isSaveKey) {
        event.preventDefault();
        event.stopPropagation();
        void saveCurrentState();
      }
    };

    const handleBeforeUnload = () => {
      if (dirtyRef.current) {
        void onSave(fileContentsRef.current);
      }
    };

    window.addEventListener("keydown", handleKeyDown);
    window.addEventListener("beforeunload", handleBeforeUnload);
    return () => {
      window.removeEventListener("keydown", handleKeyDown);
      window.removeEventListener("beforeunload", handleBeforeUnload);
      if (saveTimerRef.current) {
        window.clearTimeout(saveTimerRef.current);
      }
    };
  }, [onSave, saveCurrentState]);

  const currentContent = fileContents[activeFile] ?? "";

  return (
    <div className="editor-panel">
      <div className="file-tabs">
        {visibleFiles.map((f) => (
          <button
            key={f.path}
            type="button"
            className={`file-tab ${f.path === activeFile ? "active" : ""}`}
            onClick={() => setActiveFile(f.path)}
          >
            {f.path.split("/").pop()}
          </button>
        ))}
      </div>
      <div className="editor-container">
        <Editor
          key={`${view}:${activeFile}`}
          path={activeFile || `${view}.js`}
          height="100%"
          language={languageFromPath(activeFile)}
          value={currentContent}
          onChange={handleChange}
          onMount={(editor, monaco) => {
            editorRef.current = editor;
            window.__foruntendoSetEditorValue = (value: string) => {
              if (isReadOnly) return;
              editor.setValue(value);
            };
            editor.addCommand(monaco.KeyMod.CtrlCmd | monaco.KeyCode.Enter, () => {
              runTestsRef.current();
            });
            editor.addCommand(
              monaco.KeyMod.CtrlCmd | monaco.KeyMod.Shift | monaco.KeyCode.Enter,
              () => {
                runTestsRef.current();
              },
            );
            editor.addCommand(monaco.KeyMod.CtrlCmd | monaco.KeyCode.KeyS, () => {
              void saveCurrentStateRef.current();
            });
          }}
          theme={theme}
          options={{
            minimap: { enabled: false },
            fontSize,
            fontFamily: "'Geist Mono', ui-monospace, 'Cascadia Code', Consolas, monospace",
            lineNumbers: "on",
            scrollBeyondLastLine: false,
            automaticLayout: true,
            tabSize: 2,
            wordWrap: "on",
            padding: { top: 12 },
            readOnly: isReadOnly,
            readOnlyMessage: { value: "Тесты доступны для чтения." },
          }}
        />
      </div>
    </div>
  );
}

// apps/platform/src/components/editor/EditorPanel.svelte
<script lang="ts">
  import { onMount, onDestroy } from 'svelte';
  import * as monaco from 'monaco-editor';
  import EditorWorker from 'monaco-editor/esm/vs/editor/editor.worker?worker';
  import CssWorker from 'monaco-editor/esm/vs/language/css/css.worker?worker';
  import JsonWorker from 'monaco-editor/esm/vs/language/json/json.worker?worker';
  import TypeScriptWorker from 'monaco-editor/esm/vs/language/typescript/ts.worker?worker';
  import type { ChallengeFile } from '@codenesis/challenges';

  declare global {
    interface Window {
      __codenesisSetEditorValue?: (value: string) => void;
      MonacoEnvironment?: {
        getWorker: (_moduleId: string, label: string) => Worker;
      };
    }
  }

  window.MonacoEnvironment = {
    getWorker: (_moduleId, label) => {
      if (label === 'json') return new JsonWorker();
      if (label === 'css' || label === 'scss' || label === 'less') return new CssWorker();
      if (label === 'typescript' || label === 'javascript') return new TypeScriptWorker();
      return new EditorWorker();
    },
  };

  export let files: ChallengeFile[] = [];
  export let fullTestFiles: ChallengeFile[] = [];
  export let view: 'code' | 'tests' | 'full-tests' = 'code';
  export let theme = 'vs-dark';
  export let fontSize = 14;
  export let onFileChange: (path: string, content: string) => void = () => {};
  export let onRunTests: () => void = () => {};
  export let onSave: (files: Record<string, string>) => Promise<void> | void = () => {};

  let container: HTMLDivElement | null = null;
  let editor: monaco.editor.IStandaloneCodeEditor | undefined;
  let activeFile = '';
  let contents: Record<string, string> = {};
  let saveTimer: ReturnType<typeof setTimeout> | undefined;
  let dirty = false;

  $: allFiles = [...files, ...fullTestFiles.filter((f) => !files.some((x) => x.path === f.path))];
  $: editableFiles = files.filter((f) => !f.path.includes('.test.') && f.path !== 'package.json');
  $: testFiles = files.filter((f) => f.path.includes('.test.'));
  $: visibleFiles = view === 'full-tests' ? fullTestFiles : view === 'tests' ? testFiles : editableFiles;
  $: readOnly = view !== 'code';
  $: if (!visibleFiles.some((f) => f.path === activeFile)) activeFile = visibleFiles[0]?.path ?? '';
  $: if (allFiles) syncFiles(allFiles);
  $: if (editor) {
    editor.updateOptions({ readOnly, fontSize });
    monaco.editor.setModelMarkers(editor.getModel()!, 'owner', []);
  }

  function languageFromPath(path: string) {
    if (path.endsWith('.tsx')) return 'typescriptreact';
    if (path.endsWith('.ts')) return 'typescript';
    if (path.endsWith('.jsx')) return 'javascriptreact';
    if (path.endsWith('.js')) return 'javascript';
    if (path.endsWith('.css')) return 'css';
    if (path.endsWith('.html')) return 'html';
    if (path.endsWith('.json')) return 'json';
    return 'plaintext';
  }

  function syncFiles(next: ChallengeFile[]) {
    const nextContents = Object.fromEntries(next.map((f) => [f.path, f.content]));
    if (!dirty) contents = nextContents;
    if (!activeFile) activeFile = visibleFiles[0]?.path ?? '';
    if (editor && editor.getModel()?.uri.path.endsWith(activeFile) === false) mountEditor();
  }

  function mountEditor() {
    if (!container) return;
    const previousModel = editor?.getModel();
    editor?.dispose();
    previousModel?.dispose();
    const path = activeFile || `${view}.js`;
    const model = monaco.editor.createModel(contents[path] ?? '', languageFromPath(path), monaco.Uri.parse(`file:///${path}`));
    editor = monaco.editor.create(container, {
      model,
      theme,
      minimap: { enabled: false },
      fontSize,
      fontFamily: "'Geist Mono', ui-monospace, monospace",
      lineNumbers: 'on',
      scrollBeyondLastLine: false,
      automaticLayout: true,
      tabSize: 2,
      wordWrap: 'on',
      padding: { top: 12 },
      readOnly,
      readOnlyMessage: { value: 'Тесты доступны для чтения.' },
    });
    window.__codenesisSetEditorValue = (value: string) => {
      if (!readOnly) editor?.setValue(value);
    };
    editor.onDidChangeModelContent(() => {
      if (readOnly || !activeFile) return;
      const value = editor?.getValue() ?? '';
      contents = { ...contents, [activeFile]: value };
      dirty = true;
      onFileChange(activeFile, value);
      if (saveTimer) clearTimeout(saveTimer);
      saveTimer = setTimeout(() => { void onSave(contents); dirty = false; }, 5000);
    });
    editor.addCommand(monaco.KeyMod.CtrlCmd | monaco.KeyCode.Enter, onRunTests);
    editor.addCommand(monaco.KeyMod.CtrlCmd | monaco.KeyCode.KeyS, () => void saveCurrent());
  }

  async function saveCurrent() {
    if (editor && !readOnly && activeFile) {
      const value = editor.getValue().replace(/\n{3,}/g, '\n\n').replace(/^\n+/, '').replace(/\n+$/, '\n');
      if (value !== editor.getValue()) editor.setValue(value);
      contents = { ...contents, [activeFile]: value };
      onFileChange(activeFile, value);
    }
    dirty = false;
    await onSave(contents);
  }

  function selectFile(path: string) { activeFile = path; mountEditor(); }

  onMount(() => {
    syncFiles(allFiles);
    mountEditor();
    const keydown = (event: KeyboardEvent) => {
      if ((event.ctrlKey || event.metaKey) && ['s', 'ы'].includes(event.key.toLowerCase())) {
        event.preventDefault(); void saveCurrent();
      }
    };
    window.addEventListener('keydown', keydown);
    window.addEventListener('beforeunload', () => { if (dirty) void onSave(contents); });
    return () => window.removeEventListener('keydown', keydown);
  });

  onDestroy(() => {
    if (saveTimer) clearTimeout(saveTimer);
    delete window.__codenesisSetEditorValue;
    const model = editor?.getModel();
    editor?.dispose();
    model?.dispose();
  });
</script>

<div class="editor-panel">
  <div class="file-tabs">
    {#each visibleFiles as file}
      <button type="button" class:active={file.path === activeFile} class="file-tab" on:click={() => selectFile(file.path)}>{file.path.split('/').pop()}</button>
    {/each}
  </div>
  <div class="editor-container" bind:this={container}></div>
</div>
